apiVersion: batch/v1
kind: Job
metadata:
  name: program-job
  namespace: henriqueferreira
spec:
  template:
    metadata:
      labels:
        app: henriqueferreira-playlist-recommender
    spec:
      containers:
      - name: program-container
        image: henriquerotsen/tp2-program:0.2
        volumeMounts:
          - name: model-volume
            mountPath: /models
        env:
        - name: DATASET
          value: "https://homepages.dcc.ufmg.br/~cunha/hosted/cloudcomp-2023s2-datasets/2023_spotify_ds2.csv"
      volumes:
      - name: model-volume
        persistentVolumeClaim:
          claimName: project2-pv2-henriqueferreira
      restartPolicy: Never
  backoffLimit: 4