apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project2-pv2-henriqueferreira
  namespace: henriqueferreira
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      namespace: henriqueferreira
  storageClassName: default-storage-class-henriqueferreira