apiVersion: v1
kind: Service
metadata:
  name: server-service
  namespace: henriqueferreira
spec:
  selector:
    app: henriqueferreira-playlist-recommender
  ports:
  - protocol: TCP
    port: 30502
    targetPort: 30502
  type: ClusterIP